### ISSUE TITLE
:alien: Pausing web deployment

### ISSUE THREAD

**Issue by iqfareez** [iiumschedule/iium_schedule#60]
## The Problem
The web can't be deployed because **Isar 3.0.0+** still doesn't have web support. Refer: https://github.com/isar/isar/issues/686

In addition, I've created [ci-config.yml](https://github.com/iqfareez/iium_schedule/blob/master/ci-config.yml) file to define which flutter version and build targets when [build_all.yml](https://github.com/iqfareez/iium_schedule/actions/workflows/build_all.yml) is triggered. 

```
# Flutter channel: `stable` or `beta` or `master`
flutter_channel: stable

# build target. Set `true` or `false`
build_for:
  windows: true
  android: true
  web: false
```

Will re-enable the web target once Isar issue is fixed.

## Action

To experience the new features and improvements, consider using IIUM Schedule app on different platforms - Android/Windows/MacOS. Download them here: https://iiumschedule.iqfareez.com/downloads
